### ISSUE TITLE
Trying to use a teleportal after having been to Itorash will crash the game in some cases

### ISSUE THREAD

**Issue by XenoWars** [randovania/open-dread-rando#101]
If you have not visited every area that has a teleportal, and you then try to use one when they are all interlinked, the game will crash. This won't happen if you only have one teleportal open, but as soon as you open a second, it will.
This also occurs with random elevators/transports if Itorash connects to a teleport.

**Comment by henriquegemignani** [comment]
Workaround: only unlock teleportals after visiting Itorash plus all areas that include a teleportal.
