### ISSUE TITLE
Crash from Ghavora EMMI

### ISSUE THREAD

**Issue by ReillyBrogan** [randovania/open-dread-rando#104]
There appears to be a crash if you get hit by the ice sphere of the Ghavoran EMMI. XenoWars on Discord thought this might happen if the X aren't released, but from my testing it does not appear that releasing the X fixes the crash. 

System:
Ryujinx 1.1.142 on Linux (happened on earlier versions too)
Kernel 5.15.43, Mesa 22.0.4, AMD 6900XT GPU, Plasma 5.24.5 Wayland (doubt any of this matters, but mentioned for completeness)
14.1.1 Nintendo Switch Firmware
Metroid Dread v2.1.0 (romfs WAS extracted correctly as rookie mode has the correct string)
Randovania 4.5.0dev59 (run from source directory, this has happened with previous versions of Randovania too and yes I do run `prepare_virtual_env.sh` every time I run a git pull)

[spoiler.rdvgame.zip](https://github.com/randovania/open-dread-rando/files/8850406/spoiler.rdvgame.zip)
Save file: [Crash.zip](https://github.com/randovania/open-dread-rando/files/8850407/Crash.zip)

To reproduce:
1. Load profile 3 of the above save file
2. Leave to the Spin Boost Tower and enter the bottom EMMI door. 
3. Get hit by a ice sphere from the EMMI. The crash does not happen sometimes on the first hit, but in the three rounds I tested it happened reliably on the second hit.

To test if releasing the X helped the only change I made was to head through the bottom part of Ghavoran to the Elun transit, and then from there following the vanilla route until I looped back to the entrance (including fighting the boss). Then I headed back to the same Ghavoran save room used above and tried again. I did not check any of the optional sections of Elun, and did not grab any pickups in Elun. Then I re-did steps 1-3 of the above and observed that the crash was still present. I did not include the save file with the X cleared, but I can if wanted.

**Comment by duncathan** [comment]
ryujinx memory bug; does not happen on Software mode
