### ISSUE TITLE
Expand Readme

### ISSUE THREAD

**Issue by juligreen** [randovania/open-dread-rando#11]
Hey!

I hope this isn't too rude to ask, but could you explain a bit on how to use this tool in the readme? :)

**Comment by duncathan** [comment]
@juligreen I'll do a quick writeup for the readme right away, but in brief: this tool is currently intended primarily for use in [Randovania](https://github.com/randovania), which handles all of the randomization logic and generates the JSON dict required for the patcher to do its job. It's also in pre-alpha atm, so only the barest minimum features have been implemented and many are still buggy. If you have additional questions about usage feel free to join the [Randovania Discord server](https://discord.gg/M23gCxj6fw)
