### ISSUE TITLE
Dread: Ice EMMI having main power bomb gives 0 power bombs

### ISSUE THREAD

**Issue by SFJucelino** [randovania/open-dread-rando#110]
Does this also happen with other EMMI's?
The spoiler.rdvgame (as .txt in attachment) file shows how to easily construct a random game where Ice EMMI has main powerbomb. Going to the refill station shows that Samus has 0 of 0 power bombs.
[spoiler.txt](https://github.com/randovania/randovania/files/9070467/spoiler.txt)

**Comment by SFJucelino** [comment]
I looked at the issues before creating this one. Someone needs to add all known issues into github.

**Comment by duncathan** [comment]
absolutely. it's unfortunately time consuming work so your report is greatly appreciated
