### ISSUE TITLE
Remove cutscene from Hanubia - Tank Room

### ISSUE THREAD

**Issue by dyceron** [randovania/open-dread-rando#170]
The cutscene that plays when entering this room repositions Samus to the bottom left door. This could cause issues with random start/door lock rando and should be removed if possible.

https://user-images.githubusercontent.com/38679103/203588053-ea369954-7229-42fe-9661-bd50fe5b6d12.mp4

**Comment by ThanatosGit** [comment]
It can be disabled:
https://user-images.githubusercontent.com/117127188/204032198-97ed467c-14f5-4c04-9fd7-7eb863da5327.mp4
but from what I tested there is no way to destroy that bridge from above:
![image](https://user-images.githubusercontent.com/117127188/204032289-474b6cba-8132-493d-9234-9f5391d23d1c.png)

**Comment by dyceron** [comment]
That's fine that its not breakable. Later on it could always be changed to be breakable. For now, an SSC could be used to go below it, which is fine for seeds that have that enabled. The main takeaway from this is you can access the E.M.M.I. Zone from the top door logically without weird position changes.

**Comment by XenoWars** [comment]
It's also fine because going into tank room could be logical to get the item in the speed puzzle room. cutscene repositioning you could cause a softlock
