### ISSUE TITLE
Change model of PB Tank to actual Power Bomb used in game

### ISSUE THREAD

**Issue by dyceron** [randovania/open-dread-rando#176]
Rather than having the tanks and main share the same model and to reduce confusion of the two, change the tanks to use the model of the Power Bomb that appears on use. It would need to be increased in size of course, but would be a good change.

![image](https://user-images.githubusercontent.com/38679103/209572081-42a0c871-52bf-4ced-96ec-0b5c9b50c36e.png)

**Comment by henriquegemignani** [comment]
Solved by changing main pbs.
