### ISSUE TITLE
Add some form of anti-softlock to save stations 

### ISSUE THREAD

**Issue by duncathan** [randovania/open-dread-rando#20]
Add warp to start to save stations.

**Comment by henriquegemignani** [comment]
A warp to start might not be great given how dread works.
@duncathan's idea was to warp to the last save station you've used, I believe?

**Comment by duncathan** [comment]
actually, it was to allow the player to designate a save station as their "home" when they save, and then allow warping to home from other save points

**Comment by XenoWars** [comment]
Unfortunately this can also cause issues in some cases. One case being if you set the save in Burenia at the Ghavoran transport as "home", then warp back to it after having pulled the grapple block, that could block off access to Ghavoran completely if you warp back at the nav room

**Comment by duncathan** [comment]
alternative method: if we link the teleportals immediately, a simple warp to start is likely sufficient for most cases
