### ISSUE TITLE
Still more issues with Main Power Bomb from bosses

### ISSUE THREAD

**Issue by IanLuminus** [randovania/open-dread-rando#217]
#66
#110

This time, Emmi-02SM. Randovania 0.5.7, Dread 1.0.0
Permalink: DZ-bQNrGwDc1Z78XUQHEiGgOMzxbPpW4m8pTBA9W7W00_0EAAIra
seed: 1483530649
hash: TNANVRWA
Also uploading rdvgame as txt file.

I have.. not had a PB tank to pick up yet, so I don't know if grabbing one will fix it, but the core powerup itself is showing as collected on the Samus screen.

EDIT: So, I grabbed a PB tank. They are now fully usable with 1/1 ammo. Don't know if this really helps or not, but information is information, so it looks like the problem is if the main PB is on a boss, it skips the part where it issues two ammo as well (or however much, I don't change ammo tanks off their vanilla values, so idk if making it give 4 ammo would leave you with 2 usable).

https://gist.github.com/IanLuminus/be35fd7544fe6e5570f571232d1a410b#file-2023-05-16-14-29-21_dread_yojimbee-space-gooshocker-rdvgame-txt

**Comment by ThanatosGit** [comment]
Right, the bug was that you don't get any ammo with main pb on a boss/emmi.
This is already fixed but didn't make it to the current stable release of randovania (5.7.0) but will be available eventually
