### ISSUE TITLE
Hijack Adam rooms for hints/arbitrary text

### ISSUE THREAD

**Issue by henriquegemignani** [randovania/open-dread-rando#27]
This involves:
- Removing event-based Adam conversations
- Don't lock player in the room until they talk with adam
- Replacing the text with user provided text
- wishlist: create new text2speech audio for new text

**Comment by duncathan** [comment]
much of the Adam logic is handled in the level scripts, that's a good place to start

**Comment by duncathan** [comment]
fixed in #42
