### ISSUE TITLE
Mystery crash in gravity subarea of Burenia

### ISSUE THREAD

**Issue by duncathan** [randovania/open-dread-rando#29]
happened while entering from the early gravity entrance. logging wasn't enabled so reason for crash is unclear. error message suggested a null pointer. corrupt actor, perhaps?

**Comment by henriquegemignani** [comment]
Isn't that camera in a subpkg of the robots fight? maybe related?

**Comment by duncathan** [comment]
yeah I don't remember exactly what's in that subarea but it *is* in a subpkg which should help narrow things down

**Comment by duncathan** [comment]
can't reproduce on the file that crashed
