### ISSUE TITLE
Change what triggers the X release

### ISSUE THREAD

**Issue by henriquegemignani** [randovania/open-dread-rando#32]
Change to something more obvious like entering Elun, instead of touching the exit of the first morph ball tunnel

**Comment by duncathan** [comment]
this can be done by adding a Lua callback to the cutscene actor for entering elun (if it doesn't already have one) and setting the appropriate flag in that function

**Comment by duncathan** [comment]
tbh I'm kinda starting to change my mind on this one

**Comment by duncathan** [comment]
yeah I think that the logical implications of it being where it is are interesting enough to be worth keeping it as is
