### ISSUE TITLE
Grabbing pickups stops Samus's speed booster charge

### ISSUE THREAD

**Issue by ScorelessPine** [randovania/open-dread-rando#36]
I'm not sure whether this is the case for all pickups in all locations, but there are at least some instances where grabbing an item while Samus is at top speed will stop her, as shown in this clip where I started running and just held left: https://streamable.com/u5yyu3

**Comment by duncathan** [comment]
this is caused by disabling/enabling input for each pickup. I can split that off into speed/cloak specifically, and only on the first time, but there will be no way to fix this issue fully. it will still happen if you pick up cloak for the first time while speed booster is active, no matter what.
