### ISSUE TITLE
Dairon purple teleporter wide beam door disappearing under unknown circumstances

### ISSUE THREAD

**Issue by duncathan** [randovania/open-dread-rando#55]

**Comment by xmeehan** [comment]
I don't know if this is related but I've noticed that after destroying the cover for this door it will behave as an inactive door (not responding to beam attacks) while visually appearing normally. I can still open it with bombs or leaving and coming back, as well as occasionally by waiting several seconds. I also notice the same issue after destroying the missile cover door leading to the Chozo statue with vanilla super missiles in Ghavoran and possibly a few other places, though these are the ones that it's happened the most consistently.

**Comment by duncathan** [comment]
That's a different issue, see #34

**Comment by duncathan** [comment]
does not persist after a full reboot and reloading save
