### ISSUE TITLE
Energy Part in Cataris floating 1/4th of a tile above the ground

### ISSUE THREAD

**Issue by TheyCallMeXander** [randovania/open-dread-rando#65]
Found an Energy part with the model hovering above the ground in location: Z-57 Heat Room East

Generated with Randovania 4.2.0.dev61
Permalink: DZ0lHrptuLA8UOEITsufi3Wuz-gAAPyq
Using Emulator: Yuzu 943 - Vulcan - Metroid Dread 1.0.0

![1glitch1](https://user-images.githubusercontent.com/100409014/157032176-9649878a-3f89-4413-b48d-17d8ae312d51.PNG)

**Comment by henriquegemignani** [comment]
That's just how these pickups are located in the game. 

Maybe at some point they can be tweaked, but that's effort.
