### ISSUE TITLE
[Map] Flash Shift's Vanilla Location Icon/name doesn't Update

### ISSUE THREAD

**Issue by SoraHjort** [randovania/open-dread-rando#71]
The Vanilla location for Flash Shift does not get the new icon or name on the map after randomization. The item itself of course gets randomized. In the case of the screenshot below, it was actually a Missile Tank. So it does appear to be simply an issue with the map screen not getting updated.

![image](https://user-images.githubusercontent.com/18604504/163315791-77b349d4-ef4f-4f86-b294-375efd720635.png)

The run was generated on the Randovania dev build 4.3.0.dev69

Attached the spoiler incase you need that for testing.

[spoiler.txt](https://github.com/randovania/open-dread-rando/files/8486325/spoiler.txt)

**Comment by duncathan** [comment]
thank you for the report, this is a known issue but it wasn't on the tracker yet

**Comment by duncathan** [comment]
will likely get rid of the aeion cutscenes entirely and leave the pickups floating instead
